### ISSUE TITLE
Best.solution fails on example.data

### ISSUE THREAD

**Issue by abenjak** [VerenaK90/phy_clo_dy#1]
Hello,

I followed the tutorial and this command:
`fitting.result <- model.fits(read.count.matrix.prim = example.data$read.count.matrix.prim, read.count.matrix.rec = example.data$read.count.matrix.rec,
                        coverage.ratio.baf.prim = example.data$Coverage.B.alleles.prim, coverage.ratio.baf.rec = example.data$Coverage.B.alleles.rec,
                        locus = example.data$Locus.prim, sex = "male", directory = "~/")
`
produced an object called `resultlist` (96 elements, 2.8 Mb)

But then
`best.sol.per.cat <- Best.solution(resultlist)`
resulted in:
` Error in if (sum(c(p.prim[j, ], 1) * parms.prim) != 0) { : 
  missing value where TRUE/FALSE needed `

Kind regards,
Andrej

**Comment by VerenaK90** [comment]
Sorry, I did not check the page and only saw your request now. There was a bug introduced when cleaning up the functions for upload. It should work now. Sorry again!
